server:
  port: 8083
spring:
  application:
    name: Ribbon

providers:
  ribbon:
    listOfServers: localhost:8081,localhost:8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
